name: Build and Push to ECR

on:
  push:
    branches: [dev]  # change to main when ready

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::950693198730:role/GithubOIDCPushToECR
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 950693198730.dkr.ecr.us-east-1.amazonaws.com/nba-etl-lambda:latest
          platforms: linux/amd64
          provenance: false
          sbom: false
