name: Deploy Lambda Function

on:
  push:
    paths:
      - 'etl/lambda_function.py'
      - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install --target lambda-package -r requirements.txt
        cp etl/lambda_function.py lambda-package/

    - name: Zip Lambda package
      run: |
        cd lambda-package
        zip -r ../lambda-deploy.zip .

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        zip_file: lambda-deploy.zip