name: Deploy Lambda via S3

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and build zip
      run: |
        rm -rf lambda-package lambda-deploy.zip
        mkdir lambda-package
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir --target lambda-package -r requirements.txt
        cp etl/lambda_function.py lambda-package/
        cd lambda-package
        zip -r ../lambda-deploy.zip .

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload deployment package to S3
      run: |
        aws s3 cp lambda-deploy.zip s3://nba-analyzer-data-madeline/lambda/lambda-deploy.zip

    - name: Update Lambda function from S3
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket nba-analyzer-data-madeline \
          --s3-key lambda/lambda-deploy.zip
