# .github/workflows/nba-test.yml
name: Test NBA API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install nba_api pandas

      - name: Create test script
        run: |
          echo "from nba_api.stats.endpoints import playercareerstats" > test_script.py
          echo "from nba_api.stats.library.http import NBAStatsHTTP" >> test_script.py
          echo "" >> test_script.py
          echo "NBAStatsHTTP._HEADERS = {" >> test_script.py
          echo "    'Host': 'stats.nba.com'," >> test_script.py
          echo "    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'," >> test_script.py
          echo "    'Accept': 'application/json, text/plain, */*'," >> test_script.py
          echo "    'Referer': 'https://www.nba.com/'," >> test_script.py
          echo "    'x-nba-stats-origin': 'stats'," >> test_script.py
          echo "    'x-nba-stats-token': 'true'," >> test_script.py
          echo "    'Connection': 'keep-alive'," >> test_script.py
          echo "}" >> test_script.py
          echo "" >> test_script.py
          echo "career = playercareerstats.PlayerCareerStats(player_id=2544)" >> test_script.py
          echo "df = career.get_data_frames()[0]" >> test_script.py
          echo "print(df.head())" >> test_script.py

      - name: Run test script
        run: python test_script.py
